# Add a single user all fields are
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "email": "tsete@d.com",
    "fname": "ajas",
    "lname": "sindh",
    "password": "asdfasdf",
    "role": "user"
}

###

# Update user
PUT http://localhost:3001/api/users/6075bffd0a9ce8277c1e9f69
Content-Type: application/json

{
    "fname": "a",
    "lname": "b",
    "password": "password"
}
