// fname : 'Bruce',
// lname : "Wayne",
// currentYear:2,
// yearOfPassing:2022,
// cgpa: 7.47,
// sgpa: 8.50,
// portfolio: "https://helloajaysingh.me",
// github: "https://github.com",
// linkedin: "https://linkedin.com",
// resume:"https://docs.google.com/document/d/1bQbwd53IMvrZ049yerihRAcpNbhOLnWKXYfu6VlvGnA/", 