# Add a single user all fields are important
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "email": "test@email.com",
    "fname": "Bruce",
    "lname": "Wayne",
    "password": "1345BruceTest"
}