POST http://localhost:3001/api/details/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImlkIjoiNjA4NmZiODViZGMxZjYzYWQ4ZmYxNDI1IiwiZGV0YWlsIjoiNjA4YTJjYmQ4M2U3MmYyMDJjMDk3ZTJjIiwiaWF0IjoxNjIwNTY2NTg0fQ.9wNZtVuDIxOu4uavlU3YEEIbyzKa7ZmsatzjQ08IwLk

{
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQH61pSdmPsRaQ/profile-displayphoto-shrink_200_200/0/1598768066687?e=1625097600&v=beta&t=PHq0Q-89Laoq86RXFtKPjJ7o9OIiMk32C9nD3_YwUtk",
    "headline": "Lead at Developer Student Clubs l Microsoft Student Partner",
    "about": "testing about",
    "resume": "https://docs.google.com/document/d/1H2Pn9jzwn69gUS64UjTNw5nusj92blGnAk_AJjkHveo/edit?usp=sharing",
    "website": "https://helloajaysingh.me",
    "github": "https://github.com/Code-Recursion",
    "skills": "javascript,c++",
    "language": "german,english",
    "experience": 1,
    "secondary": 7.0,
    "seniorSecondary": 9.32,
    "yearOfPass": 2019,
    "currentGpa": 9.87,
    "yearOfGrad": 2021,
    "course": "B.Tech",
    "school": "XYZ shcool",
    "college": "Bansal Institute of Science and Technology",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "country": "India",
    "openToWork": true
}